# Generated by Django 4.2.6 on 2023-11-08 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='Lin',
        ),
    ]
